name: Execute Script

on:
  workflow_dispatch:
    inputs:
      user_input:
        description: 'Input your query to the LLM'
        required: true
        default: 'My Query to the LLM'
        type: string

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run the script
      run: |
        echo "User query: ${{ github.event.inputs.user_input }}"
        chmod +x query-script.sh
        ./query-script.sh "${{ github.event.inputs.user_input }}"
